<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SokoHub.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.OpenApi" Version="3.10.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.0.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="1.2.0" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SokoHub.Application\SokoHub.Application.csproj" />
    <ProjectReference Include="..\SokoHub.Contracts\SokoHub.Contracts.csproj" />
    <ProjectReference Include="..\SokoHub.Domain\SokoHub.Domain.csproj" />
    <ProjectReference Include="..\SokoHub.Infrastructure\SokoHub.Infrastructure.csproj" />
  </ItemGroup>

</Project>